name: github-Linux-Kokkos

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [main, develop]
    paths-ignore:
    - 'logos/**'
    - 'helper_scripts/**'
    - 'docker_scripts/**'
    - 'docs/**'
    - '**/*.md'

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  CI:
    name: Kokkos
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-gnu-kokkos-cpu-serial-11
          - ubuntu-gnu-kokkos-cpu-openmp-11
        build_type:
          - Release
          - Debug
        cmake_extra_args:
          - ''

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pressio/${{ matrix.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    env:
      eigen_version: 3.4.0
      num_cpus: 2 # $(cat /proc/cpuinfo | grep processor -c)

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: |
          cmake -B builddir \
            -D CMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }} \
            -D CMAKE_C_COMPILER=$CC \
            -D CMAKE_CXX_COMPILER=$CXX \
            -D CMAKE_CXX_FLAGS='-Wall -Werror' \
            -D CMAKE_INSTALL_PREFIX:PATH=../install \
            -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
            ${{ matrix.cmake_extra_args }} \
            -D PRESSIO_OPS_ENABLE_TESTS:BOOL=ON \
            -D PRESSIO_ENABLE_TPL_EIGEN:BOOL=OFF \
            -D PRESSIO_ENABLE_TPL_KOKKOS:BOOL=ON \
            -D KOKKOS_ROOT=/kokkos/install \
            -D KOKKOS_KERNELS_ROOT=/kokkos-kernels/install

      - name: Build
        run: |
          cmake --build builddir --target install

      - name: Run tests
        working-directory: builddir/tests
        run: |
          ctest -j $num_cpus --output-on-failure
